---
micronaut:
  application:
    name: cinema-application
--

---
datasources:
  default:
    url: 'jdbc:postgresql://cinema-db:5432/cinema'
    driverClassName: org.postgresql.Driver
    username: cinema
    password: 'gjitkYF[eq'
    dialect: org.hibernate.dialect.PostgreSQL10Dialect

liquibase:
  datasources:
    enabled: false
    default:
      change-log: 'classpath:changelogs/changelog.xml'
