---
micronaut:
  application:
    name: cinema-application

---
datasources.default: {}
---
micronaut:
  metrics:
    enabled: true

---
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/cinema'
    driverClassName: org.postgresql.Driver
    username: cinema
    password: 'gjitkYF[eq'
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        hbm2ddl:
          auto: create-drop
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:changelogs/changelog.xml'